services:
  - type: web
    name: ftm-ultra-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python ultrabot.py
    docker:
      dockerfilePath: ./Dockerfile
